import pandas as pd
from tqdm.auto import tqdm
from .hpa import fetch_HPA_data
from .mim import fetch_mim_summary 
from .entrez import fetch_entrez_summary 
from .uniprot import fetch_uniprot_summary
from concurrent.futures import ThreadPoolExecutor
from .utils import add_trailing_period, get_aliases

def build_user_prompt(ensembl_id: str, 
                      hgnc_symbol: str, 
                      entrez_id: str, 
                      mim_mapping_table: pd.DataFrame, 
                      mim_api_key: str, 
                      entrez_email: str, 
                      entrez_api_key : str = None, 
                      include_aliases: bool = True) -> str: 
    """
    Generate a user prompt for a single gene, which is then used by the LLM to summarize its' functionality. 

    Parameters
    ----------
    ensembl_id : ``str``
        A string specifying the Ensembl ID of the gene of interest.
    hgnc_symbol : ``str``
        A string specifying the HGNC symbol of the gene of interest.
    entrez_id : ``str``
        A string specifying the Entrez ID of the gene of interest.
    mim_mapping_table : ``pd.DataFrame``
        A ``pd.DataFrame`` containing the mapping from MIM ID to Ensembl ID as generated by ``fetch_mim_table()``. 
    mim_api_key : ``str``
        A string specifying `your API key`_ for the MIM database.
    entrez_email : ``str``
        A string specifying your email address that will be associated with the Entrez query. 
    entrez_api_key : ``str``
        A string specifying `your optional API key`_ for the Entrez database. Providing your key allows more API requests per second (10 versus 3). Defaults to None.
    include_aliases : ``bool``
        A Boolean specifying whether to include information concerning known HGNC gene symbol aliases in the user prompt. Defaults to True.

    Returns
    -------
        A somewhat long string containing the generated per-gene user prompt. 

    .. _your API key: https://www.omim.org/api
    .. _your optional API key: https://support.nlm.nih.gov/kbArticle/?pn=KA-05317
    """
    hpa_data = fetch_HPA_data(ensembl_id=ensembl_id)
    go_bp_terms = hpa_data['go_bp_terms']
    diseases = hpa_data['diseases']
    uniprot_info = fetch_uniprot_summary(ensembl_id=ensembl_id)
    if uniprot_info['uniprot_functions'] is None:
        uniprot_summary = None 
    elif len(uniprot_info['uniprot_functions']) > 1:
        uniprot_summary = ' '.join(uniprot_info['uniprot_functions'])
    else:
        uniprot_summary = uniprot_info['uniprot_functions'][0]
    if entrez_api_key is not None:
        entrez_summary = fetch_entrez_summary(
            entrez_id=entrez_id, 
            entrez_email=entrez_email, 
            entrez_api_key=entrez_api_key
        )
    else:
        entrez_summary = fetch_entrez_summary(entrez_id=entrez_id, entrez_email=entrez_email)
    mim_info = fetch_mim_summary(
        ensembl_id=ensembl_id, 
        mapping_table=mim_mapping_table, 
        mim_api_key=mim_api_key
    )
    if mim_info['mim_summary'] is None:
        mim_summary = None
    elif len(mim_info['mim_summary']) > 1:
        mim_summary = ' '.join(mim_info['mim_summary'])
    else: 
        mim_summary = mim_info['mim_summary'][0]
    identity_blocks = [f'- **Target Gene**: {hgnc_symbol}']
    if include_aliases:
        alias_data = get_aliases(hgnc_symbol=hgnc_symbol)
        if alias_data.get('aliases'):
            joined_aliases = ', '.join(alias_data['aliases'])
            identity_blocks.append(f'- **Aliases**: {joined_aliases}')
    identity_blocks.append(f'- **Ensembl ID**: {ensembl_id}')
    identity_blocks.append(f'- **Entrez ID**: {entrez_id}')
    identity_text = '\n'.join(identity_blocks)

    context_blocks = []
    if go_bp_terms is not None:
        context_blocks.append(f'- **HPA GO:BP Terms**: {go_bp_terms}')
    if diseases is not None:
        context_blocks.append(f'- **HPA Implicated Diseases**: {diseases}')
    if mim_info['mim_summary'] is not None:
        context_blocks.append(f'- **MIM Summary**: {mim_summary}')
    if uniprot_summary is not None:
        context_blocks.append(f'- **UniProt Summary**: {uniprot_summary}')
    if entrez_summary is not None:
        context_blocks.append(f"- **Entrez Summary**: {entrez_summary['entrez_summary']}")
    context_text = '\n'.join(context_blocks)
    prompt_user = f"""# Gene Identity
{identity_text}

# Functional Summaries
Below is information on the target gene collected from several different databases.

<gene_data>
{context_text}
</gene_data>

# Instructions
Please coalesce the various summaries above into a short description of the gene's function. Your response must fulfill the following criteria:

1. **Function Description**: Compose a short description of at most 3-4 concise sentences, using only the provided information.
2. **Confidence Score**: Provide a robust, 3-decimal score ranging from 0-1 estimating how confident you are in your summarization.
3. **Confidence Score Rationale**: Accompany your score with a brief 1-2 sentence rationale justifying your estimate.
"""
    prompt_user = add_trailing_period(text=prompt_user.strip())
    return prompt_user

def build_prompt_df(gene_list: list, 
                    gene_id_table: pd.DataFrame, 
                    mim_mapping_table: pd.DataFrame, 
                    mim_api_key: str, 
                    entrez_email: str, 
                    entrez_api_key : str = None,
                    n_workers: int = 6, 
                    progress_bar: bool = True) -> pd.DataFrame:
    """
    Generate all LLM summarization user prompts for a given list of genes in parallel.

    Parameters
    ----------
    gene_list : ``list``
        A list of all individual genes (HGNC symbols) you'd like to summarize. 
    gene_id_table : ``pd.DataFrame``
        The ``pd.DataFrame`` returned by ``fetch_gene_table()``. 
    mim_mapping_table : ``pd.DataFrame``
        A ``pd.DataFrame`` containing the mapping from MIM ID to Ensembl ID as generated by ``fetch_mim_table()``. 
    mim_api_key : ``str``
        A string specifying `your API key`_ for the MIM database.
    entrez_email : ``str``
        A string specifying your email address that will be associated with the Entrez query. 
    entrez_api_key : ``str``
        A string specifying `your optional API key`_ for the Entrez database. Providing your key allows more API requests per second (10 versus 3). Defaults to None.
    n_workers : ``int``
        An integer specifying the number of workers to use for parallel processing. Defaults to 6.
    progress_bar : ``bool``
        A Boolean specifying whether to display a progress bar during user prompt generation. Recommended for interactive notebook usage, but should probably be set to False for script usage. Defaults to True.

    Returns
    -------
        The inputted ``pd.DataFrame`` with an added column denoted 'prompt_user' containing the constructed user prompts for each gene. 

    .. _your API key: https://www.omim.org/api
    .. _your optional API key: https://support.nlm.nih.gov/kbArticle/?pn=KA-05317
    """
    mask = gene_id_table['hgnc_symbol'].isin(values=gene_list)
    gene_id_table = gene_id_table[mask].copy()
    gene_id_table.dropna(inplace=True)
    def fetch_prompt(row):
        return build_user_prompt(
            ensembl_id=row.ensembl_id, 
            hgnc_symbol=row.hgnc_symbol, 
            entrez_id=row.entrez_id, 
            mim_mapping_table=mim_mapping_table, 
            mim_api_key=mim_api_key, 
            entrez_email=entrez_email, 
            entrez_api_key=entrez_api_key,
            include_aliases=True
        )
    rows = list(gene_id_table.itertuples(index=False))
    with ThreadPoolExecutor(max_workers=n_workers) as executor:
        iterator = executor.map(fetch_prompt, rows)
        if progress_bar:
            res = list(
                tqdm(
                    iterator, 
                    total=len(rows), 
                    desc='Building gene-level prompts'
                )
            )
        else:
            res = list(iterator)
    gene_id_table['prompt_user'] = res
    return gene_id_table
